name: StarWars_Swift

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
        matrix:
          destination: [ 'generic/platform=iOS' ]

    steps:
      - uses: fwal/setup-swift@2040b795e5c453c3a05fcb8316496afc8a74f192
        with:
          swift-version: ${{ matrix.swift }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Force Xcode 11
        run: sudo xcode-select -switch /Applications/Xcode.app
        
      - name: Build App   # Build app
        run: xcodebuild -project "StarWars2.xcodeproj" -scheme "StarWars2" -destination "generic/platform=iOS" -configuration Debug build CODE_SIGNING_ALLOWED=NO
        env: 
         destination: ${{ matrix.destination }}

      
      - name: Release Build App
        run: xcodebuild -project "StarWars2.xcodeproj" -scheme "StarWars2" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
        env: 
         destination: ${{ matrix.destination }}
