name: StarWars_Swift

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
        matrix:
          destination: [ 'generic/platform=iOS' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Force Xcode 11
        run: sudo xcode-select -switch /Applications/Xcode.app
      - name: Build
        run: |
          xcodebuild clean build -project StarWars2.xcodeproj -scheme StarWars2 -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
      - name: Test
        run: |
          xcodebuild clean test -project StarWars2.xcodeproj -scheme StarWars2Tests -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      - name: Build App
        run: xcodebuild -project "MyApp.xcodeproj" -scheme "MyApp" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
        env: 
         destination: ${{ matrix.destination }}
