name: StarWars_Swift

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
        matrix:
          destination: [ 'generic/platform=iOS' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Force Xcode 11
        run: sudo xcode-select -switch /Applications/Xcode.app
      - name: Build App
        run: xcodebuild -project "StarWars2.xcodeproj" -scheme "StarWars2" -destination "generic/platform=iOS" -configuration Debug build CODE_SIGNING_ALLOWED=NO
        env: 
         destination: ${{ matrix.destination }}
     
      - name: Test
        run: |
          xcodebuild clean test -project StarWars2.xcodeproj -scheme StarWars2 -destination 'platform=iOS Simulator, id=E90AC0C5-6DA1-4BD7-83DB-12A526D8F068, OS=15.0, name=iPhone 13 Pro Max' test
      - name: Check Tests Passed 
        if: steps.xcodebuild.outputs.result != 0 
        run: exit 1
      - name: Build App
        run: xcodebuild -project "StarWars2.xcodeproj" -scheme "StarWars2" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
        env: 
         destination: ${{ matrix.destination }}
